CREATE TABLE IF NOT EXISTS task (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(7) NOT NULL
);
